image: node:latest

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  variables:
    PUBLIC_URL: https://elijahgreen.gitlab.io/audiogata
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
