/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlugininstallRouteImport } from './routes/plugininstall'
import { Route as NowplayingRouteImport } from './routes/nowplaying'
import { Route as LyricsRouteImport } from './routes/lyrics'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FavoritesRouteRouteImport } from './routes/favorites/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PluginsIndexRouteImport } from './routes/plugins.index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists.index'
import { Route as TracksTrackIdRouteImport } from './routes/tracks.$trackId'
import { Route as FavoritesTracksRouteImport } from './routes/favorites/tracks'
import { Route as FavoritesPlaylistsRouteImport } from './routes/favorites/playlists'
import { Route as FavoritesArtistsRouteImport } from './routes/favorites/artists'
import { Route as FavoritesAlbumsRouteImport } from './routes/favorites/albums'
import { Route as PluginsPluginIdIndexRouteImport } from './routes/plugins/$pluginId.index'
import { Route as PlaylistsPlaylistIdIndexRouteImport } from './routes/playlists/$playlistId.index'
import { Route as PluginsPluginIdOptionsRouteImport } from './routes/plugins/$pluginId/options'
import { Route as PluginsPluginIdLibraryRouteImport } from './routes/plugins/$pluginId/library'
import { Route as PluginsPluginIdAlbumsLibraryRouteImport } from './routes/plugins/$pluginId/albums-library'
import { Route as PluginsPluginIdPlaylistsIndexRouteImport } from './routes/plugins/$pluginId/playlists.index'
import { Route as PluginsPluginIdPlaylistsApiIdRouteImport } from './routes/plugins/$pluginId/playlists.$apiId'
import { Route as PluginsPluginIdArtistsApiIdRouteImport } from './routes/plugins/$pluginId/artists.$apiId'
import { Route as PluginsPluginIdAlbumsApiIdRouteImport } from './routes/plugins/$pluginId/albums.$apiId'
import { Route as PlaylistsPlaylistIdTracksTrackIdRouteImport } from './routes/playlists/$playlistId.tracks.$trackId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlugininstallRoute = PlugininstallRouteImport.update({
  id: '/plugininstall',
  path: '/plugininstall',
  getParentRoute: () => rootRouteImport,
} as any)
const NowplayingRoute = NowplayingRouteImport.update({
  id: '/nowplaying',
  path: '/nowplaying',
  getParentRoute: () => rootRouteImport,
} as any)
const LyricsRoute = LyricsRouteImport.update({
  id: '/lyrics',
  path: '/lyrics',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRouteRoute = FavoritesRouteRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksTrackIdRoute = TracksTrackIdRouteImport.update({
  id: '/tracks/$trackId',
  path: '/tracks/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesTracksRoute = FavoritesTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => FavoritesRouteRoute,
} as any)
const FavoritesPlaylistsRoute = FavoritesPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => FavoritesRouteRoute,
} as any)
const FavoritesArtistsRoute = FavoritesArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => FavoritesRouteRoute,
} as any)
const FavoritesAlbumsRoute = FavoritesAlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => FavoritesRouteRoute,
} as any)
const PluginsPluginIdIndexRoute = PluginsPluginIdIndexRouteImport.update({
  id: '/plugins/$pluginId/',
  path: '/plugins/$pluginId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsPlaylistIdIndexRoute =
  PlaylistsPlaylistIdIndexRouteImport.update({
    id: '/playlists/$playlistId/',
    path: '/playlists/$playlistId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdOptionsRoute = PluginsPluginIdOptionsRouteImport.update({
  id: '/plugins/$pluginId/options',
  path: '/plugins/$pluginId/options',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdLibraryRoute = PluginsPluginIdLibraryRouteImport.update({
  id: '/plugins/$pluginId/library',
  path: '/plugins/$pluginId/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdAlbumsLibraryRoute =
  PluginsPluginIdAlbumsLibraryRouteImport.update({
    id: '/plugins/$pluginId/albums-library',
    path: '/plugins/$pluginId/albums-library',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdPlaylistsIndexRoute =
  PluginsPluginIdPlaylistsIndexRouteImport.update({
    id: '/plugins/$pluginId/playlists/',
    path: '/plugins/$pluginId/playlists/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdPlaylistsApiIdRoute =
  PluginsPluginIdPlaylistsApiIdRouteImport.update({
    id: '/plugins/$pluginId/playlists/$apiId',
    path: '/plugins/$pluginId/playlists/$apiId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdArtistsApiIdRoute =
  PluginsPluginIdArtistsApiIdRouteImport.update({
    id: '/plugins/$pluginId/artists/$apiId',
    path: '/plugins/$pluginId/artists/$apiId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdAlbumsApiIdRoute =
  PluginsPluginIdAlbumsApiIdRouteImport.update({
    id: '/plugins/$pluginId/albums/$apiId',
    path: '/plugins/$pluginId/albums/$apiId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlaylistsPlaylistIdTracksTrackIdRoute =
  PlaylistsPlaylistIdTracksTrackIdRouteImport.update({
    id: '/playlists/$playlistId/tracks/$trackId',
    path: '/playlists/$playlistId/tracks/$trackId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/lyrics': typeof LyricsRoute
  '/nowplaying': typeof NowplayingRoute
  '/plugininstall': typeof PlugininstallRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/favorites/albums': typeof FavoritesAlbumsRoute
  '/favorites/artists': typeof FavoritesArtistsRoute
  '/favorites/playlists': typeof FavoritesPlaylistsRoute
  '/favorites/tracks': typeof FavoritesTracksRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/$pluginId/albums-library': typeof PluginsPluginIdAlbumsLibraryRoute
  '/plugins/$pluginId/library': typeof PluginsPluginIdLibraryRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/playlists/$playlistId/': typeof PlaylistsPlaylistIdIndexRoute
  '/plugins/$pluginId/': typeof PluginsPluginIdIndexRoute
  '/playlists/$playlistId/tracks/$trackId': typeof PlaylistsPlaylistIdTracksTrackIdRoute
  '/plugins/$pluginId/albums/$apiId': typeof PluginsPluginIdAlbumsApiIdRoute
  '/plugins/$pluginId/artists/$apiId': typeof PluginsPluginIdArtistsApiIdRoute
  '/plugins/$pluginId/playlists/$apiId': typeof PluginsPluginIdPlaylistsApiIdRoute
  '/plugins/$pluginId/playlists/': typeof PluginsPluginIdPlaylistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/lyrics': typeof LyricsRoute
  '/nowplaying': typeof NowplayingRoute
  '/plugininstall': typeof PlugininstallRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/favorites/albums': typeof FavoritesAlbumsRoute
  '/favorites/artists': typeof FavoritesArtistsRoute
  '/favorites/playlists': typeof FavoritesPlaylistsRoute
  '/favorites/tracks': typeof FavoritesTracksRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/plugins': typeof PluginsIndexRoute
  '/plugins/$pluginId/albums-library': typeof PluginsPluginIdAlbumsLibraryRoute
  '/plugins/$pluginId/library': typeof PluginsPluginIdLibraryRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdIndexRoute
  '/plugins/$pluginId': typeof PluginsPluginIdIndexRoute
  '/playlists/$playlistId/tracks/$trackId': typeof PlaylistsPlaylistIdTracksTrackIdRoute
  '/plugins/$pluginId/albums/$apiId': typeof PluginsPluginIdAlbumsApiIdRoute
  '/plugins/$pluginId/artists/$apiId': typeof PluginsPluginIdArtistsApiIdRoute
  '/plugins/$pluginId/playlists/$apiId': typeof PluginsPluginIdPlaylistsApiIdRoute
  '/plugins/$pluginId/playlists': typeof PluginsPluginIdPlaylistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/lyrics': typeof LyricsRoute
  '/nowplaying': typeof NowplayingRoute
  '/plugininstall': typeof PlugininstallRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/favorites/albums': typeof FavoritesAlbumsRoute
  '/favorites/artists': typeof FavoritesArtistsRoute
  '/favorites/playlists': typeof FavoritesPlaylistsRoute
  '/favorites/tracks': typeof FavoritesTracksRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/$pluginId/albums-library': typeof PluginsPluginIdAlbumsLibraryRoute
  '/plugins/$pluginId/library': typeof PluginsPluginIdLibraryRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/playlists/$playlistId/': typeof PlaylistsPlaylistIdIndexRoute
  '/plugins/$pluginId/': typeof PluginsPluginIdIndexRoute
  '/playlists/$playlistId/tracks/$trackId': typeof PlaylistsPlaylistIdTracksTrackIdRoute
  '/plugins/$pluginId/albums/$apiId': typeof PluginsPluginIdAlbumsApiIdRoute
  '/plugins/$pluginId/artists/$apiId': typeof PluginsPluginIdArtistsApiIdRoute
  '/plugins/$pluginId/playlists/$apiId': typeof PluginsPluginIdPlaylistsApiIdRoute
  '/plugins/$pluginId/playlists/': typeof PluginsPluginIdPlaylistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/about'
    | '/donate'
    | '/lyrics'
    | '/nowplaying'
    | '/plugininstall'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/favorites/albums'
    | '/favorites/artists'
    | '/favorites/playlists'
    | '/favorites/tracks'
    | '/tracks/$trackId'
    | '/playlists/'
    | '/plugins/'
    | '/plugins/$pluginId/albums-library'
    | '/plugins/$pluginId/library'
    | '/plugins/$pluginId/options'
    | '/playlists/$playlistId/'
    | '/plugins/$pluginId/'
    | '/playlists/$playlistId/tracks/$trackId'
    | '/plugins/$pluginId/albums/$apiId'
    | '/plugins/$pluginId/artists/$apiId'
    | '/plugins/$pluginId/playlists/$apiId'
    | '/plugins/$pluginId/playlists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/about'
    | '/donate'
    | '/lyrics'
    | '/nowplaying'
    | '/plugininstall'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/favorites/albums'
    | '/favorites/artists'
    | '/favorites/playlists'
    | '/favorites/tracks'
    | '/tracks/$trackId'
    | '/playlists'
    | '/plugins'
    | '/plugins/$pluginId/albums-library'
    | '/plugins/$pluginId/library'
    | '/plugins/$pluginId/options'
    | '/playlists/$playlistId'
    | '/plugins/$pluginId'
    | '/playlists/$playlistId/tracks/$trackId'
    | '/plugins/$pluginId/albums/$apiId'
    | '/plugins/$pluginId/artists/$apiId'
    | '/plugins/$pluginId/playlists/$apiId'
    | '/plugins/$pluginId/playlists'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/about'
    | '/donate'
    | '/lyrics'
    | '/nowplaying'
    | '/plugininstall'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/favorites/albums'
    | '/favorites/artists'
    | '/favorites/playlists'
    | '/favorites/tracks'
    | '/tracks/$trackId'
    | '/playlists/'
    | '/plugins/'
    | '/plugins/$pluginId/albums-library'
    | '/plugins/$pluginId/library'
    | '/plugins/$pluginId/options'
    | '/playlists/$playlistId/'
    | '/plugins/$pluginId/'
    | '/playlists/$playlistId/tracks/$trackId'
    | '/plugins/$pluginId/albums/$apiId'
    | '/plugins/$pluginId/artists/$apiId'
    | '/plugins/$pluginId/playlists/$apiId'
    | '/plugins/$pluginId/playlists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRouteRoute: typeof FavoritesRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DonateRoute: typeof DonateRoute
  LyricsRoute: typeof LyricsRoute
  NowplayingRoute: typeof NowplayingRoute
  PlugininstallRoute: typeof PlugininstallRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TracksTrackIdRoute: typeof TracksTrackIdRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  PluginsPluginIdAlbumsLibraryRoute: typeof PluginsPluginIdAlbumsLibraryRoute
  PluginsPluginIdLibraryRoute: typeof PluginsPluginIdLibraryRoute
  PluginsPluginIdOptionsRoute: typeof PluginsPluginIdOptionsRoute
  PlaylistsPlaylistIdIndexRoute: typeof PlaylistsPlaylistIdIndexRoute
  PluginsPluginIdIndexRoute: typeof PluginsPluginIdIndexRoute
  PlaylistsPlaylistIdTracksTrackIdRoute: typeof PlaylistsPlaylistIdTracksTrackIdRoute
  PluginsPluginIdAlbumsApiIdRoute: typeof PluginsPluginIdAlbumsApiIdRoute
  PluginsPluginIdArtistsApiIdRoute: typeof PluginsPluginIdArtistsApiIdRoute
  PluginsPluginIdPlaylistsApiIdRoute: typeof PluginsPluginIdPlaylistsApiIdRoute
  PluginsPluginIdPlaylistsIndexRoute: typeof PluginsPluginIdPlaylistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugininstall': {
      id: '/plugininstall'
      path: '/plugininstall'
      fullPath: '/plugininstall'
      preLoaderRoute: typeof PlugininstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nowplaying': {
      id: '/nowplaying'
      path: '/nowplaying'
      fullPath: '/nowplaying'
      preLoaderRoute: typeof NowplayingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lyrics': {
      id: '/lyrics'
      path: '/lyrics'
      fullPath: '/lyrics'
      preLoaderRoute: typeof LyricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/$trackId': {
      id: '/tracks/$trackId'
      path: '/tracks/$trackId'
      fullPath: '/tracks/$trackId'
      preLoaderRoute: typeof TracksTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/tracks': {
      id: '/favorites/tracks'
      path: '/tracks'
      fullPath: '/favorites/tracks'
      preLoaderRoute: typeof FavoritesTracksRouteImport
      parentRoute: typeof FavoritesRouteRoute
    }
    '/favorites/playlists': {
      id: '/favorites/playlists'
      path: '/playlists'
      fullPath: '/favorites/playlists'
      preLoaderRoute: typeof FavoritesPlaylistsRouteImport
      parentRoute: typeof FavoritesRouteRoute
    }
    '/favorites/artists': {
      id: '/favorites/artists'
      path: '/artists'
      fullPath: '/favorites/artists'
      preLoaderRoute: typeof FavoritesArtistsRouteImport
      parentRoute: typeof FavoritesRouteRoute
    }
    '/favorites/albums': {
      id: '/favorites/albums'
      path: '/albums'
      fullPath: '/favorites/albums'
      preLoaderRoute: typeof FavoritesAlbumsRouteImport
      parentRoute: typeof FavoritesRouteRoute
    }
    '/plugins/$pluginId/': {
      id: '/plugins/$pluginId/'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId/'
      preLoaderRoute: typeof PluginsPluginIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$playlistId/': {
      id: '/playlists/$playlistId/'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId/'
      preLoaderRoute: typeof PlaylistsPlaylistIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/options': {
      id: '/plugins/$pluginId/options'
      path: '/plugins/$pluginId/options'
      fullPath: '/plugins/$pluginId/options'
      preLoaderRoute: typeof PluginsPluginIdOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/library': {
      id: '/plugins/$pluginId/library'
      path: '/plugins/$pluginId/library'
      fullPath: '/plugins/$pluginId/library'
      preLoaderRoute: typeof PluginsPluginIdLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/albums-library': {
      id: '/plugins/$pluginId/albums-library'
      path: '/plugins/$pluginId/albums-library'
      fullPath: '/plugins/$pluginId/albums-library'
      preLoaderRoute: typeof PluginsPluginIdAlbumsLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/playlists/': {
      id: '/plugins/$pluginId/playlists/'
      path: '/plugins/$pluginId/playlists'
      fullPath: '/plugins/$pluginId/playlists/'
      preLoaderRoute: typeof PluginsPluginIdPlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/playlists/$apiId': {
      id: '/plugins/$pluginId/playlists/$apiId'
      path: '/plugins/$pluginId/playlists/$apiId'
      fullPath: '/plugins/$pluginId/playlists/$apiId'
      preLoaderRoute: typeof PluginsPluginIdPlaylistsApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/artists/$apiId': {
      id: '/plugins/$pluginId/artists/$apiId'
      path: '/plugins/$pluginId/artists/$apiId'
      fullPath: '/plugins/$pluginId/artists/$apiId'
      preLoaderRoute: typeof PluginsPluginIdArtistsApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/albums/$apiId': {
      id: '/plugins/$pluginId/albums/$apiId'
      path: '/plugins/$pluginId/albums/$apiId'
      fullPath: '/plugins/$pluginId/albums/$apiId'
      preLoaderRoute: typeof PluginsPluginIdAlbumsApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$playlistId/tracks/$trackId': {
      id: '/playlists/$playlistId/tracks/$trackId'
      path: '/playlists/$playlistId/tracks/$trackId'
      fullPath: '/playlists/$playlistId/tracks/$trackId'
      preLoaderRoute: typeof PlaylistsPlaylistIdTracksTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FavoritesRouteRouteChildren {
  FavoritesAlbumsRoute: typeof FavoritesAlbumsRoute
  FavoritesArtistsRoute: typeof FavoritesArtistsRoute
  FavoritesPlaylistsRoute: typeof FavoritesPlaylistsRoute
  FavoritesTracksRoute: typeof FavoritesTracksRoute
}

const FavoritesRouteRouteChildren: FavoritesRouteRouteChildren = {
  FavoritesAlbumsRoute: FavoritesAlbumsRoute,
  FavoritesArtistsRoute: FavoritesArtistsRoute,
  FavoritesPlaylistsRoute: FavoritesPlaylistsRoute,
  FavoritesTracksRoute: FavoritesTracksRoute,
}

const FavoritesRouteRouteWithChildren = FavoritesRouteRoute._addFileChildren(
  FavoritesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRouteRoute: FavoritesRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DonateRoute: DonateRoute,
  LyricsRoute: LyricsRoute,
  NowplayingRoute: NowplayingRoute,
  PlugininstallRoute: PlugininstallRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TracksTrackIdRoute: TracksTrackIdRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  PluginsPluginIdAlbumsLibraryRoute: PluginsPluginIdAlbumsLibraryRoute,
  PluginsPluginIdLibraryRoute: PluginsPluginIdLibraryRoute,
  PluginsPluginIdOptionsRoute: PluginsPluginIdOptionsRoute,
  PlaylistsPlaylistIdIndexRoute: PlaylistsPlaylistIdIndexRoute,
  PluginsPluginIdIndexRoute: PluginsPluginIdIndexRoute,
  PlaylistsPlaylistIdTracksTrackIdRoute: PlaylistsPlaylistIdTracksTrackIdRoute,
  PluginsPluginIdAlbumsApiIdRoute: PluginsPluginIdAlbumsApiIdRoute,
  PluginsPluginIdArtistsApiIdRoute: PluginsPluginIdArtistsApiIdRoute,
  PluginsPluginIdPlaylistsApiIdRoute: PluginsPluginIdPlaylistsApiIdRoute,
  PluginsPluginIdPlaylistsIndexRoute: PluginsPluginIdPlaylistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
