/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as SearchImport } from './routes/search'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as PlugininstallImport } from './routes/plugininstall'
import { Route as NowplayingImport } from './routes/nowplaying'
import { Route as LyricsImport } from './routes/lyrics'
import { Route as DonateImport } from './routes/donate'
import { Route as AboutImport } from './routes/about'
import { Route as FavoritesRouteImport } from './routes/favorites/route'
import { Route as IndexImport } from './routes/index'
import { Route as PluginsIndexImport } from './routes/plugins.index'
import { Route as PlaylistsIndexImport } from './routes/playlists.index'
import { Route as TracksTrackIdImport } from './routes/tracks.$trackId'
import { Route as FavoritesTracksImport } from './routes/favorites/tracks'
import { Route as FavoritesPlaylistsImport } from './routes/favorites/playlists'
import { Route as FavoritesArtistsImport } from './routes/favorites/artists'
import { Route as FavoritesAlbumsImport } from './routes/favorites/albums'
import { Route as PluginsPluginIdIndexImport } from './routes/plugins/$pluginId.index'
import { Route as PlaylistsPlaylistIdIndexImport } from './routes/playlists/$playlistId.index'
import { Route as PluginsPluginIdOptionsImport } from './routes/plugins/$pluginId/options'
import { Route as PluginsPluginIdPlaylistsIndexImport } from './routes/plugins/$pluginId/playlists.index'
import { Route as PluginsPluginIdPlaylistsApiIdImport } from './routes/plugins/$pluginId/playlists.$apiId'
import { Route as PluginsPluginIdArtistsApiIdImport } from './routes/plugins/$pluginId/artists.$apiId'
import { Route as PluginsPluginIdAlbumsApiIdImport } from './routes/plugins/$pluginId/albums.$apiId'
import { Route as PlaylistsPlaylistIdTracksTrackIdImport } from './routes/playlists/$playlistId.tracks.$trackId'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const PlugininstallRoute = PlugininstallImport.update({
  path: '/plugininstall',
  getParentRoute: () => rootRoute,
} as any)

const NowplayingRoute = NowplayingImport.update({
  path: '/nowplaying',
  getParentRoute: () => rootRoute,
} as any)

const LyricsRoute = LyricsImport.update({
  path: '/lyrics',
  getParentRoute: () => rootRoute,
} as any)

const DonateRoute = DonateImport.update({
  path: '/donate',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const FavoritesRouteRoute = FavoritesRouteImport.update({
  path: '/favorites',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PluginsIndexRoute = PluginsIndexImport.update({
  path: '/plugins/',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistsIndexRoute = PlaylistsIndexImport.update({
  path: '/playlists/',
  getParentRoute: () => rootRoute,
} as any)

const TracksTrackIdRoute = TracksTrackIdImport.update({
  path: '/tracks/$trackId',
  getParentRoute: () => rootRoute,
} as any)

const FavoritesTracksRoute = FavoritesTracksImport.update({
  path: '/tracks',
  getParentRoute: () => FavoritesRouteRoute,
} as any)

const FavoritesPlaylistsRoute = FavoritesPlaylistsImport.update({
  path: '/playlists',
  getParentRoute: () => FavoritesRouteRoute,
} as any)

const FavoritesArtistsRoute = FavoritesArtistsImport.update({
  path: '/artists',
  getParentRoute: () => FavoritesRouteRoute,
} as any)

const FavoritesAlbumsRoute = FavoritesAlbumsImport.update({
  path: '/albums',
  getParentRoute: () => FavoritesRouteRoute,
} as any)

const PluginsPluginIdIndexRoute = PluginsPluginIdIndexImport.update({
  path: '/plugins/$pluginId/',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistsPlaylistIdIndexRoute = PlaylistsPlaylistIdIndexImport.update({
  path: '/playlists/$playlistId/',
  getParentRoute: () => rootRoute,
} as any)

const PluginsPluginIdOptionsRoute = PluginsPluginIdOptionsImport.update({
  path: '/plugins/$pluginId/options',
  getParentRoute: () => rootRoute,
} as any)

const PluginsPluginIdPlaylistsIndexRoute =
  PluginsPluginIdPlaylistsIndexImport.update({
    path: '/plugins/$pluginId/playlists/',
    getParentRoute: () => rootRoute,
  } as any)

const PluginsPluginIdPlaylistsApiIdRoute =
  PluginsPluginIdPlaylistsApiIdImport.update({
    path: '/plugins/$pluginId/playlists/$apiId',
    getParentRoute: () => rootRoute,
  } as any)

const PluginsPluginIdArtistsApiIdRoute =
  PluginsPluginIdArtistsApiIdImport.update({
    path: '/plugins/$pluginId/artists/$apiId',
    getParentRoute: () => rootRoute,
  } as any)

const PluginsPluginIdAlbumsApiIdRoute = PluginsPluginIdAlbumsApiIdImport.update(
  {
    path: '/plugins/$pluginId/albums/$apiId',
    getParentRoute: () => rootRoute,
  } as any,
)

const PlaylistsPlaylistIdTracksTrackIdRoute =
  PlaylistsPlaylistIdTracksTrackIdImport.update({
    path: '/playlists/$playlistId/tracks/$trackId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateImport
      parentRoute: typeof rootRoute
    }
    '/lyrics': {
      id: '/lyrics'
      path: '/lyrics'
      fullPath: '/lyrics'
      preLoaderRoute: typeof LyricsImport
      parentRoute: typeof rootRoute
    }
    '/nowplaying': {
      id: '/nowplaying'
      path: '/nowplaying'
      fullPath: '/nowplaying'
      preLoaderRoute: typeof NowplayingImport
      parentRoute: typeof rootRoute
    }
    '/plugininstall': {
      id: '/plugininstall'
      path: '/plugininstall'
      fullPath: '/plugininstall'
      preLoaderRoute: typeof PlugininstallImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/favorites/albums': {
      id: '/favorites/albums'
      path: '/albums'
      fullPath: '/favorites/albums'
      preLoaderRoute: typeof FavoritesAlbumsImport
      parentRoute: typeof FavoritesRouteImport
    }
    '/favorites/artists': {
      id: '/favorites/artists'
      path: '/artists'
      fullPath: '/favorites/artists'
      preLoaderRoute: typeof FavoritesArtistsImport
      parentRoute: typeof FavoritesRouteImport
    }
    '/favorites/playlists': {
      id: '/favorites/playlists'
      path: '/playlists'
      fullPath: '/favorites/playlists'
      preLoaderRoute: typeof FavoritesPlaylistsImport
      parentRoute: typeof FavoritesRouteImport
    }
    '/favorites/tracks': {
      id: '/favorites/tracks'
      path: '/tracks'
      fullPath: '/favorites/tracks'
      preLoaderRoute: typeof FavoritesTracksImport
      parentRoute: typeof FavoritesRouteImport
    }
    '/tracks/$trackId': {
      id: '/tracks/$trackId'
      path: '/tracks/$trackId'
      fullPath: '/tracks/$trackId'
      preLoaderRoute: typeof TracksTrackIdImport
      parentRoute: typeof rootRoute
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsIndexImport
      parentRoute: typeof rootRoute
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsIndexImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/options': {
      id: '/plugins/$pluginId/options'
      path: '/plugins/$pluginId/options'
      fullPath: '/plugins/$pluginId/options'
      preLoaderRoute: typeof PluginsPluginIdOptionsImport
      parentRoute: typeof rootRoute
    }
    '/playlists/$playlistId/': {
      id: '/playlists/$playlistId/'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/': {
      id: '/plugins/$pluginId/'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof PluginsPluginIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/playlists/$playlistId/tracks/$trackId': {
      id: '/playlists/$playlistId/tracks/$trackId'
      path: '/playlists/$playlistId/tracks/$trackId'
      fullPath: '/playlists/$playlistId/tracks/$trackId'
      preLoaderRoute: typeof PlaylistsPlaylistIdTracksTrackIdImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/albums/$apiId': {
      id: '/plugins/$pluginId/albums/$apiId'
      path: '/plugins/$pluginId/albums/$apiId'
      fullPath: '/plugins/$pluginId/albums/$apiId'
      preLoaderRoute: typeof PluginsPluginIdAlbumsApiIdImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/artists/$apiId': {
      id: '/plugins/$pluginId/artists/$apiId'
      path: '/plugins/$pluginId/artists/$apiId'
      fullPath: '/plugins/$pluginId/artists/$apiId'
      preLoaderRoute: typeof PluginsPluginIdArtistsApiIdImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/playlists/$apiId': {
      id: '/plugins/$pluginId/playlists/$apiId'
      path: '/plugins/$pluginId/playlists/$apiId'
      fullPath: '/plugins/$pluginId/playlists/$apiId'
      preLoaderRoute: typeof PluginsPluginIdPlaylistsApiIdImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/playlists/': {
      id: '/plugins/$pluginId/playlists/'
      path: '/plugins/$pluginId/playlists'
      fullPath: '/plugins/$pluginId/playlists'
      preLoaderRoute: typeof PluginsPluginIdPlaylistsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  FavoritesRouteRoute: FavoritesRouteRoute.addChildren({
    FavoritesAlbumsRoute,
    FavoritesArtistsRoute,
    FavoritesPlaylistsRoute,
    FavoritesTracksRoute,
  }),
  AboutRoute,
  DonateRoute,
  LyricsRoute,
  NowplayingRoute,
  PlugininstallRoute,
  PrivacyRoute,
  SearchRoute,
  SettingsRoute,
  TracksTrackIdRoute,
  PlaylistsIndexRoute,
  PluginsIndexRoute,
  PluginsPluginIdOptionsRoute,
  PlaylistsPlaylistIdIndexRoute,
  PluginsPluginIdIndexRoute,
  PlaylistsPlaylistIdTracksTrackIdRoute,
  PluginsPluginIdAlbumsApiIdRoute,
  PluginsPluginIdArtistsApiIdRoute,
  PluginsPluginIdPlaylistsApiIdRoute,
  PluginsPluginIdPlaylistsIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/favorites",
        "/about",
        "/donate",
        "/lyrics",
        "/nowplaying",
        "/plugininstall",
        "/privacy",
        "/search",
        "/settings",
        "/tracks/$trackId",
        "/playlists/",
        "/plugins/",
        "/plugins/$pluginId/options",
        "/playlists/$playlistId/",
        "/plugins/$pluginId/",
        "/playlists/$playlistId/tracks/$trackId",
        "/plugins/$pluginId/albums/$apiId",
        "/plugins/$pluginId/artists/$apiId",
        "/plugins/$pluginId/playlists/$apiId",
        "/plugins/$pluginId/playlists/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/favorites": {
      "filePath": "favorites/route.tsx",
      "children": [
        "/favorites/albums",
        "/favorites/artists",
        "/favorites/playlists",
        "/favorites/tracks"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/donate": {
      "filePath": "donate.tsx"
    },
    "/lyrics": {
      "filePath": "lyrics.tsx"
    },
    "/nowplaying": {
      "filePath": "nowplaying.tsx"
    },
    "/plugininstall": {
      "filePath": "plugininstall.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/favorites/albums": {
      "filePath": "favorites/albums.tsx",
      "parent": "/favorites"
    },
    "/favorites/artists": {
      "filePath": "favorites/artists.tsx",
      "parent": "/favorites"
    },
    "/favorites/playlists": {
      "filePath": "favorites/playlists.tsx",
      "parent": "/favorites"
    },
    "/favorites/tracks": {
      "filePath": "favorites/tracks.tsx",
      "parent": "/favorites"
    },
    "/tracks/$trackId": {
      "filePath": "tracks.$trackId.tsx"
    },
    "/playlists/": {
      "filePath": "playlists.index.tsx"
    },
    "/plugins/": {
      "filePath": "plugins.index.tsx"
    },
    "/plugins/$pluginId/options": {
      "filePath": "plugins/$pluginId/options.tsx"
    },
    "/playlists/$playlistId/": {
      "filePath": "playlists/$playlistId.index.tsx"
    },
    "/plugins/$pluginId/": {
      "filePath": "plugins/$pluginId.index.tsx"
    },
    "/playlists/$playlistId/tracks/$trackId": {
      "filePath": "playlists/$playlistId.tracks.$trackId.tsx"
    },
    "/plugins/$pluginId/albums/$apiId": {
      "filePath": "plugins/$pluginId/albums.$apiId.tsx"
    },
    "/plugins/$pluginId/artists/$apiId": {
      "filePath": "plugins/$pluginId/artists.$apiId.tsx"
    },
    "/plugins/$pluginId/playlists/$apiId": {
      "filePath": "plugins/$pluginId/playlists.$apiId.tsx"
    },
    "/plugins/$pluginId/playlists/": {
      "filePath": "plugins/$pluginId/playlists.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
