/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as SearchImport } from './routes/search'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as PlugininstallImport } from './routes/plugininstall'
import { Route as NowplayingImport } from './routes/nowplaying'
import { Route as LyricsImport } from './routes/lyrics'
import { Route as DonateImport } from './routes/donate'
import { Route as AboutImport } from './routes/about'
import { Route as FavoritesRouteImport } from './routes/favorites/route'
import { Route as IndexImport } from './routes/index'
import { Route as PluginsIndexImport } from './routes/plugins.index'
import { Route as PlaylistsIndexImport } from './routes/playlists.index'
import { Route as TracksTrackIdImport } from './routes/tracks.$trackId'
import { Route as FavoritesTracksImport } from './routes/favorites/tracks'
import { Route as FavoritesPlaylistsImport } from './routes/favorites/playlists'
import { Route as FavoritesArtistsImport } from './routes/favorites/artists'
import { Route as FavoritesAlbumsImport } from './routes/favorites/albums'
import { Route as PluginsPluginIdIndexImport } from './routes/plugins/$pluginId.index'
import { Route as PlaylistsPlaylistIdIndexImport } from './routes/playlists/$playlistId.index'
import { Route as PluginsPluginIdOptionsImport } from './routes/plugins/$pluginId/options'
import { Route as PluginsPluginIdLibraryImport } from './routes/plugins/$pluginId/library'
import { Route as PluginsPluginIdAlbumsLibraryImport } from './routes/plugins/$pluginId/albums-library'
import { Route as PluginsPluginIdPlaylistsIndexImport } from './routes/plugins/$pluginId/playlists.index'
import { Route as PluginsPluginIdPlaylistsApiIdImport } from './routes/plugins/$pluginId/playlists.$apiId'
import { Route as PluginsPluginIdArtistsApiIdImport } from './routes/plugins/$pluginId/artists.$apiId'
import { Route as PluginsPluginIdAlbumsApiIdImport } from './routes/plugins/$pluginId/albums.$apiId'
import { Route as PlaylistsPlaylistIdTracksTrackIdImport } from './routes/playlists/$playlistId.tracks.$trackId'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const PlugininstallRoute = PlugininstallImport.update({
  id: '/plugininstall',
  path: '/plugininstall',
  getParentRoute: () => rootRoute,
} as any)

const NowplayingRoute = NowplayingImport.update({
  id: '/nowplaying',
  path: '/nowplaying',
  getParentRoute: () => rootRoute,
} as any)

const LyricsRoute = LyricsImport.update({
  id: '/lyrics',
  path: '/lyrics',
  getParentRoute: () => rootRoute,
} as any)

const DonateRoute = DonateImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const FavoritesRouteRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PluginsIndexRoute = PluginsIndexImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistsIndexRoute = PlaylistsIndexImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRoute,
} as any)

const TracksTrackIdRoute = TracksTrackIdImport.update({
  id: '/tracks/$trackId',
  path: '/tracks/$trackId',
  getParentRoute: () => rootRoute,
} as any)

const FavoritesTracksRoute = FavoritesTracksImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => FavoritesRouteRoute,
} as any)

const FavoritesPlaylistsRoute = FavoritesPlaylistsImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => FavoritesRouteRoute,
} as any)

const FavoritesArtistsRoute = FavoritesArtistsImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => FavoritesRouteRoute,
} as any)

const FavoritesAlbumsRoute = FavoritesAlbumsImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => FavoritesRouteRoute,
} as any)

const PluginsPluginIdIndexRoute = PluginsPluginIdIndexImport.update({
  id: '/plugins/$pluginId/',
  path: '/plugins/$pluginId/',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistsPlaylistIdIndexRoute = PlaylistsPlaylistIdIndexImport.update({
  id: '/playlists/$playlistId/',
  path: '/playlists/$playlistId/',
  getParentRoute: () => rootRoute,
} as any)

const PluginsPluginIdOptionsRoute = PluginsPluginIdOptionsImport.update({
  id: '/plugins/$pluginId/options',
  path: '/plugins/$pluginId/options',
  getParentRoute: () => rootRoute,
} as any)

const PluginsPluginIdLibraryRoute = PluginsPluginIdLibraryImport.update({
  id: '/plugins/$pluginId/library',
  path: '/plugins/$pluginId/library',
  getParentRoute: () => rootRoute,
} as any)

const PluginsPluginIdAlbumsLibraryRoute =
  PluginsPluginIdAlbumsLibraryImport.update({
    id: '/plugins/$pluginId/albums-library',
    path: '/plugins/$pluginId/albums-library',
    getParentRoute: () => rootRoute,
  } as any)

const PluginsPluginIdPlaylistsIndexRoute =
  PluginsPluginIdPlaylistsIndexImport.update({
    id: '/plugins/$pluginId/playlists/',
    path: '/plugins/$pluginId/playlists/',
    getParentRoute: () => rootRoute,
  } as any)

const PluginsPluginIdPlaylistsApiIdRoute =
  PluginsPluginIdPlaylistsApiIdImport.update({
    id: '/plugins/$pluginId/playlists/$apiId',
    path: '/plugins/$pluginId/playlists/$apiId',
    getParentRoute: () => rootRoute,
  } as any)

const PluginsPluginIdArtistsApiIdRoute =
  PluginsPluginIdArtistsApiIdImport.update({
    id: '/plugins/$pluginId/artists/$apiId',
    path: '/plugins/$pluginId/artists/$apiId',
    getParentRoute: () => rootRoute,
  } as any)

const PluginsPluginIdAlbumsApiIdRoute = PluginsPluginIdAlbumsApiIdImport.update(
  {
    id: '/plugins/$pluginId/albums/$apiId',
    path: '/plugins/$pluginId/albums/$apiId',
    getParentRoute: () => rootRoute,
  } as any,
)

const PlaylistsPlaylistIdTracksTrackIdRoute =
  PlaylistsPlaylistIdTracksTrackIdImport.update({
    id: '/playlists/$playlistId/tracks/$trackId',
    path: '/playlists/$playlistId/tracks/$trackId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateImport
      parentRoute: typeof rootRoute
    }
    '/lyrics': {
      id: '/lyrics'
      path: '/lyrics'
      fullPath: '/lyrics'
      preLoaderRoute: typeof LyricsImport
      parentRoute: typeof rootRoute
    }
    '/nowplaying': {
      id: '/nowplaying'
      path: '/nowplaying'
      fullPath: '/nowplaying'
      preLoaderRoute: typeof NowplayingImport
      parentRoute: typeof rootRoute
    }
    '/plugininstall': {
      id: '/plugininstall'
      path: '/plugininstall'
      fullPath: '/plugininstall'
      preLoaderRoute: typeof PlugininstallImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/favorites/albums': {
      id: '/favorites/albums'
      path: '/albums'
      fullPath: '/favorites/albums'
      preLoaderRoute: typeof FavoritesAlbumsImport
      parentRoute: typeof FavoritesRouteImport
    }
    '/favorites/artists': {
      id: '/favorites/artists'
      path: '/artists'
      fullPath: '/favorites/artists'
      preLoaderRoute: typeof FavoritesArtistsImport
      parentRoute: typeof FavoritesRouteImport
    }
    '/favorites/playlists': {
      id: '/favorites/playlists'
      path: '/playlists'
      fullPath: '/favorites/playlists'
      preLoaderRoute: typeof FavoritesPlaylistsImport
      parentRoute: typeof FavoritesRouteImport
    }
    '/favorites/tracks': {
      id: '/favorites/tracks'
      path: '/tracks'
      fullPath: '/favorites/tracks'
      preLoaderRoute: typeof FavoritesTracksImport
      parentRoute: typeof FavoritesRouteImport
    }
    '/tracks/$trackId': {
      id: '/tracks/$trackId'
      path: '/tracks/$trackId'
      fullPath: '/tracks/$trackId'
      preLoaderRoute: typeof TracksTrackIdImport
      parentRoute: typeof rootRoute
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsIndexImport
      parentRoute: typeof rootRoute
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsIndexImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/albums-library': {
      id: '/plugins/$pluginId/albums-library'
      path: '/plugins/$pluginId/albums-library'
      fullPath: '/plugins/$pluginId/albums-library'
      preLoaderRoute: typeof PluginsPluginIdAlbumsLibraryImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/library': {
      id: '/plugins/$pluginId/library'
      path: '/plugins/$pluginId/library'
      fullPath: '/plugins/$pluginId/library'
      preLoaderRoute: typeof PluginsPluginIdLibraryImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/options': {
      id: '/plugins/$pluginId/options'
      path: '/plugins/$pluginId/options'
      fullPath: '/plugins/$pluginId/options'
      preLoaderRoute: typeof PluginsPluginIdOptionsImport
      parentRoute: typeof rootRoute
    }
    '/playlists/$playlistId/': {
      id: '/playlists/$playlistId/'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/': {
      id: '/plugins/$pluginId/'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof PluginsPluginIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/playlists/$playlistId/tracks/$trackId': {
      id: '/playlists/$playlistId/tracks/$trackId'
      path: '/playlists/$playlistId/tracks/$trackId'
      fullPath: '/playlists/$playlistId/tracks/$trackId'
      preLoaderRoute: typeof PlaylistsPlaylistIdTracksTrackIdImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/albums/$apiId': {
      id: '/plugins/$pluginId/albums/$apiId'
      path: '/plugins/$pluginId/albums/$apiId'
      fullPath: '/plugins/$pluginId/albums/$apiId'
      preLoaderRoute: typeof PluginsPluginIdAlbumsApiIdImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/artists/$apiId': {
      id: '/plugins/$pluginId/artists/$apiId'
      path: '/plugins/$pluginId/artists/$apiId'
      fullPath: '/plugins/$pluginId/artists/$apiId'
      preLoaderRoute: typeof PluginsPluginIdArtistsApiIdImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/playlists/$apiId': {
      id: '/plugins/$pluginId/playlists/$apiId'
      path: '/plugins/$pluginId/playlists/$apiId'
      fullPath: '/plugins/$pluginId/playlists/$apiId'
      preLoaderRoute: typeof PluginsPluginIdPlaylistsApiIdImport
      parentRoute: typeof rootRoute
    }
    '/plugins/$pluginId/playlists/': {
      id: '/plugins/$pluginId/playlists/'
      path: '/plugins/$pluginId/playlists'
      fullPath: '/plugins/$pluginId/playlists'
      preLoaderRoute: typeof PluginsPluginIdPlaylistsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface FavoritesRouteRouteChildren {
  FavoritesAlbumsRoute: typeof FavoritesAlbumsRoute
  FavoritesArtistsRoute: typeof FavoritesArtistsRoute
  FavoritesPlaylistsRoute: typeof FavoritesPlaylistsRoute
  FavoritesTracksRoute: typeof FavoritesTracksRoute
}

const FavoritesRouteRouteChildren: FavoritesRouteRouteChildren = {
  FavoritesAlbumsRoute: FavoritesAlbumsRoute,
  FavoritesArtistsRoute: FavoritesArtistsRoute,
  FavoritesPlaylistsRoute: FavoritesPlaylistsRoute,
  FavoritesTracksRoute: FavoritesTracksRoute,
}

const FavoritesRouteRouteWithChildren = FavoritesRouteRoute._addFileChildren(
  FavoritesRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/lyrics': typeof LyricsRoute
  '/nowplaying': typeof NowplayingRoute
  '/plugininstall': typeof PlugininstallRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/favorites/albums': typeof FavoritesAlbumsRoute
  '/favorites/artists': typeof FavoritesArtistsRoute
  '/favorites/playlists': typeof FavoritesPlaylistsRoute
  '/favorites/tracks': typeof FavoritesTracksRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/plugins': typeof PluginsIndexRoute
  '/plugins/$pluginId/albums-library': typeof PluginsPluginIdAlbumsLibraryRoute
  '/plugins/$pluginId/library': typeof PluginsPluginIdLibraryRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdIndexRoute
  '/plugins/$pluginId': typeof PluginsPluginIdIndexRoute
  '/playlists/$playlistId/tracks/$trackId': typeof PlaylistsPlaylistIdTracksTrackIdRoute
  '/plugins/$pluginId/albums/$apiId': typeof PluginsPluginIdAlbumsApiIdRoute
  '/plugins/$pluginId/artists/$apiId': typeof PluginsPluginIdArtistsApiIdRoute
  '/plugins/$pluginId/playlists/$apiId': typeof PluginsPluginIdPlaylistsApiIdRoute
  '/plugins/$pluginId/playlists': typeof PluginsPluginIdPlaylistsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/lyrics': typeof LyricsRoute
  '/nowplaying': typeof NowplayingRoute
  '/plugininstall': typeof PlugininstallRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/favorites/albums': typeof FavoritesAlbumsRoute
  '/favorites/artists': typeof FavoritesArtistsRoute
  '/favorites/playlists': typeof FavoritesPlaylistsRoute
  '/favorites/tracks': typeof FavoritesTracksRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/plugins': typeof PluginsIndexRoute
  '/plugins/$pluginId/albums-library': typeof PluginsPluginIdAlbumsLibraryRoute
  '/plugins/$pluginId/library': typeof PluginsPluginIdLibraryRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdIndexRoute
  '/plugins/$pluginId': typeof PluginsPluginIdIndexRoute
  '/playlists/$playlistId/tracks/$trackId': typeof PlaylistsPlaylistIdTracksTrackIdRoute
  '/plugins/$pluginId/albums/$apiId': typeof PluginsPluginIdAlbumsApiIdRoute
  '/plugins/$pluginId/artists/$apiId': typeof PluginsPluginIdArtistsApiIdRoute
  '/plugins/$pluginId/playlists/$apiId': typeof PluginsPluginIdPlaylistsApiIdRoute
  '/plugins/$pluginId/playlists': typeof PluginsPluginIdPlaylistsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/lyrics': typeof LyricsRoute
  '/nowplaying': typeof NowplayingRoute
  '/plugininstall': typeof PlugininstallRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/favorites/albums': typeof FavoritesAlbumsRoute
  '/favorites/artists': typeof FavoritesArtistsRoute
  '/favorites/playlists': typeof FavoritesPlaylistsRoute
  '/favorites/tracks': typeof FavoritesTracksRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/$pluginId/albums-library': typeof PluginsPluginIdAlbumsLibraryRoute
  '/plugins/$pluginId/library': typeof PluginsPluginIdLibraryRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/playlists/$playlistId/': typeof PlaylistsPlaylistIdIndexRoute
  '/plugins/$pluginId/': typeof PluginsPluginIdIndexRoute
  '/playlists/$playlistId/tracks/$trackId': typeof PlaylistsPlaylistIdTracksTrackIdRoute
  '/plugins/$pluginId/albums/$apiId': typeof PluginsPluginIdAlbumsApiIdRoute
  '/plugins/$pluginId/artists/$apiId': typeof PluginsPluginIdArtistsApiIdRoute
  '/plugins/$pluginId/playlists/$apiId': typeof PluginsPluginIdPlaylistsApiIdRoute
  '/plugins/$pluginId/playlists/': typeof PluginsPluginIdPlaylistsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/about'
    | '/donate'
    | '/lyrics'
    | '/nowplaying'
    | '/plugininstall'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/favorites/albums'
    | '/favorites/artists'
    | '/favorites/playlists'
    | '/favorites/tracks'
    | '/tracks/$trackId'
    | '/playlists'
    | '/plugins'
    | '/plugins/$pluginId/albums-library'
    | '/plugins/$pluginId/library'
    | '/plugins/$pluginId/options'
    | '/playlists/$playlistId'
    | '/plugins/$pluginId'
    | '/playlists/$playlistId/tracks/$trackId'
    | '/plugins/$pluginId/albums/$apiId'
    | '/plugins/$pluginId/artists/$apiId'
    | '/plugins/$pluginId/playlists/$apiId'
    | '/plugins/$pluginId/playlists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/about'
    | '/donate'
    | '/lyrics'
    | '/nowplaying'
    | '/plugininstall'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/favorites/albums'
    | '/favorites/artists'
    | '/favorites/playlists'
    | '/favorites/tracks'
    | '/tracks/$trackId'
    | '/playlists'
    | '/plugins'
    | '/plugins/$pluginId/albums-library'
    | '/plugins/$pluginId/library'
    | '/plugins/$pluginId/options'
    | '/playlists/$playlistId'
    | '/plugins/$pluginId'
    | '/playlists/$playlistId/tracks/$trackId'
    | '/plugins/$pluginId/albums/$apiId'
    | '/plugins/$pluginId/artists/$apiId'
    | '/plugins/$pluginId/playlists/$apiId'
    | '/plugins/$pluginId/playlists'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/about'
    | '/donate'
    | '/lyrics'
    | '/nowplaying'
    | '/plugininstall'
    | '/privacy'
    | '/search'
    | '/settings'
    | '/favorites/albums'
    | '/favorites/artists'
    | '/favorites/playlists'
    | '/favorites/tracks'
    | '/tracks/$trackId'
    | '/playlists/'
    | '/plugins/'
    | '/plugins/$pluginId/albums-library'
    | '/plugins/$pluginId/library'
    | '/plugins/$pluginId/options'
    | '/playlists/$playlistId/'
    | '/plugins/$pluginId/'
    | '/playlists/$playlistId/tracks/$trackId'
    | '/plugins/$pluginId/albums/$apiId'
    | '/plugins/$pluginId/artists/$apiId'
    | '/plugins/$pluginId/playlists/$apiId'
    | '/plugins/$pluginId/playlists/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRouteRoute: typeof FavoritesRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DonateRoute: typeof DonateRoute
  LyricsRoute: typeof LyricsRoute
  NowplayingRoute: typeof NowplayingRoute
  PlugininstallRoute: typeof PlugininstallRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TracksTrackIdRoute: typeof TracksTrackIdRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  PluginsPluginIdAlbumsLibraryRoute: typeof PluginsPluginIdAlbumsLibraryRoute
  PluginsPluginIdLibraryRoute: typeof PluginsPluginIdLibraryRoute
  PluginsPluginIdOptionsRoute: typeof PluginsPluginIdOptionsRoute
  PlaylistsPlaylistIdIndexRoute: typeof PlaylistsPlaylistIdIndexRoute
  PluginsPluginIdIndexRoute: typeof PluginsPluginIdIndexRoute
  PlaylistsPlaylistIdTracksTrackIdRoute: typeof PlaylistsPlaylistIdTracksTrackIdRoute
  PluginsPluginIdAlbumsApiIdRoute: typeof PluginsPluginIdAlbumsApiIdRoute
  PluginsPluginIdArtistsApiIdRoute: typeof PluginsPluginIdArtistsApiIdRoute
  PluginsPluginIdPlaylistsApiIdRoute: typeof PluginsPluginIdPlaylistsApiIdRoute
  PluginsPluginIdPlaylistsIndexRoute: typeof PluginsPluginIdPlaylistsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRouteRoute: FavoritesRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DonateRoute: DonateRoute,
  LyricsRoute: LyricsRoute,
  NowplayingRoute: NowplayingRoute,
  PlugininstallRoute: PlugininstallRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TracksTrackIdRoute: TracksTrackIdRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  PluginsPluginIdAlbumsLibraryRoute: PluginsPluginIdAlbumsLibraryRoute,
  PluginsPluginIdLibraryRoute: PluginsPluginIdLibraryRoute,
  PluginsPluginIdOptionsRoute: PluginsPluginIdOptionsRoute,
  PlaylistsPlaylistIdIndexRoute: PlaylistsPlaylistIdIndexRoute,
  PluginsPluginIdIndexRoute: PluginsPluginIdIndexRoute,
  PlaylistsPlaylistIdTracksTrackIdRoute: PlaylistsPlaylistIdTracksTrackIdRoute,
  PluginsPluginIdAlbumsApiIdRoute: PluginsPluginIdAlbumsApiIdRoute,
  PluginsPluginIdArtistsApiIdRoute: PluginsPluginIdArtistsApiIdRoute,
  PluginsPluginIdPlaylistsApiIdRoute: PluginsPluginIdPlaylistsApiIdRoute,
  PluginsPluginIdPlaylistsIndexRoute: PluginsPluginIdPlaylistsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/favorites",
        "/about",
        "/donate",
        "/lyrics",
        "/nowplaying",
        "/plugininstall",
        "/privacy",
        "/search",
        "/settings",
        "/tracks/$trackId",
        "/playlists/",
        "/plugins/",
        "/plugins/$pluginId/albums-library",
        "/plugins/$pluginId/library",
        "/plugins/$pluginId/options",
        "/playlists/$playlistId/",
        "/plugins/$pluginId/",
        "/playlists/$playlistId/tracks/$trackId",
        "/plugins/$pluginId/albums/$apiId",
        "/plugins/$pluginId/artists/$apiId",
        "/plugins/$pluginId/playlists/$apiId",
        "/plugins/$pluginId/playlists/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/favorites": {
      "filePath": "favorites/route.tsx",
      "children": [
        "/favorites/albums",
        "/favorites/artists",
        "/favorites/playlists",
        "/favorites/tracks"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/donate": {
      "filePath": "donate.tsx"
    },
    "/lyrics": {
      "filePath": "lyrics.tsx"
    },
    "/nowplaying": {
      "filePath": "nowplaying.tsx"
    },
    "/plugininstall": {
      "filePath": "plugininstall.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/favorites/albums": {
      "filePath": "favorites/albums.tsx",
      "parent": "/favorites"
    },
    "/favorites/artists": {
      "filePath": "favorites/artists.tsx",
      "parent": "/favorites"
    },
    "/favorites/playlists": {
      "filePath": "favorites/playlists.tsx",
      "parent": "/favorites"
    },
    "/favorites/tracks": {
      "filePath": "favorites/tracks.tsx",
      "parent": "/favorites"
    },
    "/tracks/$trackId": {
      "filePath": "tracks.$trackId.tsx"
    },
    "/playlists/": {
      "filePath": "playlists.index.tsx"
    },
    "/plugins/": {
      "filePath": "plugins.index.tsx"
    },
    "/plugins/$pluginId/albums-library": {
      "filePath": "plugins/$pluginId/albums-library.tsx"
    },
    "/plugins/$pluginId/library": {
      "filePath": "plugins/$pluginId/library.tsx"
    },
    "/plugins/$pluginId/options": {
      "filePath": "plugins/$pluginId/options.tsx"
    },
    "/playlists/$playlistId/": {
      "filePath": "playlists/$playlistId.index.tsx"
    },
    "/plugins/$pluginId/": {
      "filePath": "plugins/$pluginId.index.tsx"
    },
    "/playlists/$playlistId/tracks/$trackId": {
      "filePath": "playlists/$playlistId.tracks.$trackId.tsx"
    },
    "/plugins/$pluginId/albums/$apiId": {
      "filePath": "plugins/$pluginId/albums.$apiId.tsx"
    },
    "/plugins/$pluginId/artists/$apiId": {
      "filePath": "plugins/$pluginId/artists.$apiId.tsx"
    },
    "/plugins/$pluginId/playlists/$apiId": {
      "filePath": "plugins/$pluginId/playlists.$apiId.tsx"
    },
    "/plugins/$pluginId/playlists/": {
      "filePath": "plugins/$pluginId/playlists.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
